---
# image: docker:dind
# services:
#   - docker:dind


stages:
 - build

build:
 stage:build
   image:docker:20.10.8-dind
  #  image: docker:dind
#  image: centos:latest
#  image: python:3.9-slim 1
 script:
  - pwd
  - ls -la
  - docker --version
  - docker build .

