# image: docker:20.10.8
# services:
#   - docker:20.10.8-dind


stages:
 - build


build:
 stage: build
#  image: centos:latest
 image: python:3.9-slim
 script:
  - pwd
  - ls -la
  - docker build .

